name: hw2_automl
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.12=h2bbff1b_0
  - pip=23.3.1=py310haa95532_0
  - python=3.10.13=he1021f5_0
  - setuptools=68.2.2=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - alembic==1.13.1
    - anyio==4.2.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.14.0
    - beautifulsoup4==4.12.2
    - bleach==6.1.0
    - blinker==1.7.0
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - comm==0.2.0
    - contourpy==1.2.0
    - cycler==0.12.1
    - databricks-cli==0.18.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker==6.1.3
    - entrypoints==0.4
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - flask==3.0.0
    - fonttools==4.47.0
    - fqdn==1.5.1
    - gitdb==4.0.11
    - gitpython==3.1.40
    - greenlet==3.0.3
    - idna==3.6
    - importlib-metadata==7.0.1
    - ipykernel==6.28.0
    - ipython==8.19.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.0
    - jupyter-console==6.6.3
    - jupyter-core==5.5.1
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.1
    - jupyter-server==2.12.1
    - jupyter-server-terminals==0.5.1
    - jupyterlab==4.0.9
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.2
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.5
    - mako==1.3.0
    - markdown==3.5.1
    - markupsafe==2.1.3
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - mlflow==2.9.2
    - nbclient==0.9.0
    - nbconvert==7.13.1
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - numpy==1.26.2
    - oauthlib==3.2.2
    - overrides==7.4.0
    - packaging==23.2
    - pandas==2.1.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pillow==10.1.0
    - platformdirs==4.1.0
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.43
    - protobuf==4.25.1
    - psutil==5.9.7
    - pure-eval==0.2.2
    - pyarrow==14.0.2
    - pycparser==2.21
    - pygments==2.17.2
    - pyjwt==2.8.0
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3.post1
    - pywin32==306
    - pywinpty==2.0.12
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - querystring-parser==1.2.4
    - referencing==0.32.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.16.2
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - seaborn==0.13.0
    - send2trash==1.8.2
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - sqlalchemy==2.0.24
    - sqlparse==0.4.4
    - stack-data==0.6.3
    - tabulate==0.9.0
    - terminado==0.18.0
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - tornado==6.4
    - traitlets==5.14.0
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.9.0
    - tzdata==2023.3
    - uri-template==1.3.0
    - urllib3==2.1.0
    - waitress==2.1.2
    - wcwidth==0.2.12
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - werkzeug==3.0.1
    - widgetsnbextension==4.0.9
    - xgboost==2.0.3
    - zipp==3.17.0
prefix: C:\Users\mikol\anaconda3\envs\hw2_automl
